name:                typecore
version:             0.1.0.0
github:              "githubuser/typecore"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/typecore#readme>

dependencies:
- base >= 4.7 && < 5
- clash-lib
- clash-prelude
# - clash-cosim
- ghc-typelits-natnormalise
- ghc-typelits-extra
- ghc-typelits-knownnat
- parsec
- raw-strings-qq
- containers
- split
build-tools:
- clash-ghc


default-extensions:
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DeriveLift
- DerivingStrategies
- ExplicitForAll
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- KindSignatures
- MagicHash
- MonoLocalBinds
- QuasiQuotes
- ScopedTypeVariables
- TemplateHaskell
- TemplateHaskellQuotes
- TypeApplications
- TypeFamilies
- TypeOperators
- NoImplicitPrelude
- NoMonomorphismRestriction
- NoStrict
- NoStrictData
- PartialTypeSignatures
- ViewPatterns

ghc-options:
- -fplugin=GHC.TypeLits.Normalise
- -fplugin=GHC.TypeLits.Extra.Solver
- -fplugin=GHC.TypeLits.KnownNat.Solver
- -Wall


library:
  source-dirs: src

executables:
  typecore-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typecore

tests:
  typecore-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typecore
